In [1]:
import numpy as np

In [3]:
l1=np.array([1,2,3,4]);
l2=np.array([1,3,5,7]);
gr=np.greater(l1,l2);
gt=np.greater_equal(l1,l2);
le=np.less(l1,l2);
lt=np.less_equal(l1,l2);
eq=np.equal(l1,l2);
print("greater ",gr,"greater equal ",gt,"less ",le,"Less than or equal",le,"equal");


greater  [False False False False] greater equal  [ True False False False] less  [False  True  True  True] Less than or equal [False  True  True  True] equal


In [4]:
l=np.arange(20,51,2);
l

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50])

In [5]:
iden=np.identity(4,dtype=int);
iden

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [6]:
diag=np.diag([1,2,3,4,5])
diag

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [7]:
n=np.arange(1,21)
print(n)
for i in n:
    if i>=9 and i<=15:
        n[i]=i*-1
print(n)         

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[  1   2   3   4   5   6   7   8   9  -9  11 -11  13 -13  15 -15  17  18
  19  20]


In [11]:
n=[[1,2],[3,4]]
a=np.array(n)
print(a)
print("sum",a.sum())
print("Sum of cols ",a.sum(0))
print("Sum of rows ",a.sum(1))

[[1 2]
 [3 4]]
sum 10
Sum of cols  [4 6]
Sum of rows  [3 7]
