In [1]:
import numpy as np

In [2]:
matrix1=[]
matrix2=[]
r1,c1=list(map(int,input("Enter the rows and cols for mat1 ").split()))
r2,c2=list(map(int,input("Enter the rows and cols for mat2 ").split()))
m=list(map(int,input("Enter the first mat ").split()))
matrix1.append(m)
m1=np.array(matrix1).reshape(r1,c1);
m=list(map(int,input("Enter the Second mat ").split()))
matrix2.append(m)
m2=np.array(matrix2).reshape(r2,c2);
print("Matrix 1 /n ")
print(m1)
print("Matrix 2 /n ")
print(m2)



Matrix 1 /n 
[[1 2]
 [3 4]]
Matrix 2 /n 
[[2 4]
 [6 8]]


i. Dot Product
ii. Transpose
iii. Determinant
iv. Inverse
v. Trace
vi. Rank
vii. Eigen values and Eigen vectors

In [3]:
product=m1.dot(m2)
product

array([[14, 20],
       [30, 44]])

In [4]:
trasns=np.transpose(m1)
trasns

array([[1, 3],
       [2, 4]])

In [5]:
deter=np.linalg.det(m1)
deter

-2.0000000000000004

In [7]:
inv=np.linalg.inv(m1)
inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [8]:
tr=np.trace(m1)
tr

5

In [9]:
rank=np.linalg.matrix_rank(m1)
rank

2

In [10]:
eig=np.linalg.eig(m1)
eig

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))